services:
  order_service:
    container_name: order_service
    ports: 
      - "8080:8080"
    build:
      context: ./order_service
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks: [order_backend, order_frontend]

networks:
  order_backend:
    driver: bridge
    external: true

  order_frontend:
    driver: bridge
    external: true
