services:
  postgres:
    image: postgres:17
    container_name: ${ORDER_POSTGRES}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${ORDER_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./order_service/db/init:/docker-entrypoint-initdb.d
    networks: [order_backend]

  redis:
    container_name: ${ORDER_REDIS}
    image: redis:8-alpine
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "${REDIS_PORT}:6379"
    networks: [order_backend]

networks:
  order_backend:
    driver: bridge
    external: true

volumes:
  redis_data:
